### ISSUE TITLE
Use new EC2 instance type API

### ISSUE THREAD

**Issue by gabegorelick** [LeanerCloud/ec2-instances-info#10]
EC2 now has a DescribeInstanceTypes API. Does it make sense to use that instead of managing the data yourself?

See https://aws.amazon.com/blogs/compute/it-just-got-easier-to-discover-and-compare-ec2-instance-types/

**Comment by cristim** [comment]
Thanks, that's a good point. 

This data is static so it is inefficient to keep fetching it on each run, so it would need some caching, which would complicate the implementation.

That data source was also not available when I started AutoSpotting and I didn't see much benefit to migrate to using it, considering that extra complexity.

When I looked into it, it was also much more inefficient from the storage perspective than the data from ec2instances.info.

Later edit: I forgot to mention that ec2instances.info uses that API call as a data source, so we're already indirectly using it.

**Comment by gabegorelick** [comment]
That makes sense. Thanks.
