### ISSUE TITLE
outdated instances.json

### ISSUE THREAD

**Issue by alexei-led** [LeanerCloud/ec2-instances-info#20]
The https://ec2instances.info/instances.json redirects to the outdated JSON file in the GitHub repository.

The https://ec2instances.info/instances.json contains 352 instances, where https://s3.amazonaws.com/www.ec2instances.info/instances.json contains 391 instances.

For example, "c6gn" instances are not listed in GitHub hosted JSON file.

**Comment by cristim** [comment]
Good catch,thanks!
